#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

error() {
	local msg="$1"
	echo "$(tput setaf 1)ERROR:$(tput sgr0) $msg" >&2
	exit 1
}

main() {
	local USAGE="usage: $0 -i VIDEO.mp4 -i AUDIO.m4a -o OUTPUT.mp4"
	local video audio output

	if (( "$EUID" == 0 )); then
		error "This script must be run as regular user (non-root)"
	fi
	if (( "$#" < 6 )); then
		error "$USAGE"
	fi
	if [[ "$1" != "-i" || "$2" == "" || "$2" == "-"* ]]; then
		error "$USAGE"
	fi
	if [[ "$3" != "-i" || "$4" == "" || "$4" == "-"* ]]; then
		error "$USAGE"
	fi
	if [[ "$5" != "-o" || "$6" == "" || "$6" == "-"* ]]; then
		error "$USAGE"
	fi

	video="$2"
	audio="$4"
	output="$6"

	ffmpeg -i "$video" -i "$audio" -vcodec copy -acodec copy "$output"
}

main "$@"
