#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

error() {
	local msg="$1"
	echo "$(tput setaf 1)ERROR:$(tput sgr0) $msg" >&2
	exit 1
}

success() {
	local msg="$1"
	echo "$(tput setaf 2)SUCCESS:$(tput sgr0) $msg"
}

main() {
	local USAGE="usage: $0 PICTURE.jpg"
	local pic
	if (( "$EUID" == 0 )); then
		error "This script must be run as regular user (non-root)"
	fi
	if (( "$#" < 1 )); then
		error "$USAGE"
	fi
	if [[ "$1" == "" || "$1" == "-"* ]]; then
		error "$USAGE"
	fi

	pic="$1"
	size="$(identify -ping -format '%[w]x%[h]' "$pic")"

	if [[ "$size" == "1080x1920" ]]; then
		success "$pic is portrait FullHD"
	else
		error "$pic is not portrait FullHD: $size"
	fi
}

main "$@"
